development:
  adapter: mysql2
  encoding: utf8
  database: derpsum
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1
  port: 3306
  
staging:
  adapter: mysql2
  encoding: utf8
  database: derpsum_staging
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1
  port: 3306